services:
  db:
    container_name: postgres
    hostname: postgres
    image: postgres:17
    environment:
      POSTGRES_USER: "${DJANGO_DATABASE_USER}"
      POSTGRES_PASSWORD: "${DJANGO_DATABASE_PWORD}"
      POSTGRES_DB: "${DJANGO_DATABASE_NAME}"
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  adminer:
    container_name: adminer
    hostname: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
  django-web:
    build: .
    container_name: django-docker
    ports:
     - "8000:8000"
    depends_on:
     - db
    environment:
     DJANGO_SECRET_KEY: ${DJANGO_SECRET}
     DEBUG: ${DEBUG}
     DJANGO_LOGLEVEL: ${DJANGO_LOGLEVEL}
     DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
     DATABASE_ENGINE: ${DJANGO_DATABASE_ENGINE}
     DATABASE_NAME: ${DJANGO_DATABASE_NAME}
     DATABASE_USERNAME: ${DJANGO_DATABASE_USER}
     DATABASE_PASSWORD: ${DJANGO_DATABASE_PWORD}
     DATABASE_HOST: ${DJANGO_DATABASE_HOST}
     DATABASE_PORT: ${DJANGO_DATABASE_PORT}
    env_file:
     - .env
    volumes:
     - .:/app
  
volumes:
  postgres_data: